[package]
name = "poise-test"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
poise = { git = "https://github.com/serenity-rs/poise.git", branch = "next", version = "0.6.1" }
tokio = { version = "1.41.1", features = ["rt-multi-thread", "tokio-macros"] }
